// Pi Coding Agent runtime adapter for overstory's AgentRuntime interface.
// Pi (https://github.com/badlogic/pi-mono) is an MIT-licensed coding agent
// with RPC mode, 324+ models across 20+ providers, and an in-process
// TypeScript extension system that replaces Claude Code's hook mechanism.
//
// See docs/runtime-abstraction.md "Pi Integration" for design rationale.

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ResolvedModel } from "../types.ts";
import type {
	AgentRuntime,
	HooksDef,
	OverlayContent,
	ReadyState,
	SpawnOpts,
	TranscriptSummary,
} from "./types.ts";

/**
 * Generate the TypeScript source for an overstory guard extension.
 *
 * Pi's extension system replaces Claude Code's PreToolUse hooks. The guard
 * extension subscribes to `tool_call` events and returns `{type:"block"}`
 * for dangerous operations, equivalent to the hook returning `{"decision":"block"}`.
 *
 * The generated extension enforces:
 * 1. Path boundaries — blocks file writes outside the worktree
 * 2. Read-only agents — scouts/reviewers cannot write files or run destructive commands
 * 3. Dangerous git operations — no force-push, no push to canonical branch
 * 4. Quality gates — (placeholder for future gate enforcement)
 */
function generateGuardExtension(hooks: HooksDef): string {
	const isReadOnly = ["scout", "reviewer", "monitor"].includes(hooks.capability);
	const worktreePath = hooks.worktreePath.replace(/\\/g, "/");

	return `// Auto-generated by overstory for agent: ${hooks.agentName}
// Capability: ${hooks.capability} | Read-only: ${isReadOnly}
// DO NOT EDIT — regenerated on each agent spawn.

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function(pi: ExtensionAPI) {
  const WORKTREE = "${worktreePath}";
  const READ_ONLY = ${isReadOnly};
  const AGENT_NAME = "${hooks.agentName}";

  // Dangerous bash patterns (same as hooks-deployer.ts blocklist)
  const BLOCKED_BASH = [
    /\\bgit\\s+push\\s+.*--force(?!-with-lease)/,
    /\\bgit\\s+push\\s+(-[^\\s]*)*-f\\b/,
    /\\bgit\\s+push\\s+[^-]*\\b(main|master|develop)\\b/,
    /\\bgit\\s+reset\\s+--hard\\b/,
    /\\bgit\\s+clean\\s+(-[^\\s]*)*-[fd]/,
    /\\brm\\s+(-[^\\s]*)*-[rRf]/,
    /\\bsudo\\b/,
    /\\bchmod\\s+(-[^\\s]+\\s+)*777\\b/,
  ];

  // Read-only agents: block all writes
  const WRITE_BLOCKED_BASH = [
    /\\bgit\\s+commit\\b/,
    /\\bgit\\s+merge\\b/,
    /\\bgit\\s+rebase\\b/,
    /\\bgit\\s+cherry-pick\\b/,
  ];

  pi.on("tool_call", (event) => {
    const name = event.name;
    const input = event.input ?? {};

    // Block file writes outside worktree
    if (name === "write" || name === "edit") {
      const filePath = (input.path ?? "").replace(/\\\\\\\\/g, "/");
      if (!filePath.startsWith(WORKTREE) && !filePath.startsWith("./")) {
        return { type: "block", reason: \`[\${AGENT_NAME}] Path outside worktree: \${filePath}\` };
      }
      if (READ_ONLY) {
        return { type: "block", reason: \`[\${AGENT_NAME}] Read-only agent cannot write files\` };
      }
    }

    // Block dangerous bash commands
    if (name === "bash") {
      const cmd = input.command ?? "";
      for (const pattern of BLOCKED_BASH) {
        if (pattern.test(cmd)) {
          return { type: "block", reason: \`[\${AGENT_NAME}] Blocked dangerous command: \${cmd.slice(0, 80)}\` };
        }
      }
      if (READ_ONLY) {
        for (const pattern of WRITE_BLOCKED_BASH) {
          if (pattern.test(cmd)) {
            return { type: "block", reason: \`[\${AGENT_NAME}] Read-only agent cannot run: \${cmd.slice(0, 80)}\` };
          }
        }
      }
    }

    return { type: "allow" };
  });
}
`;
}

/**
 * Pi Coding Agent runtime adapter.
 *
 * Implements AgentRuntime for the `pi` CLI (@mariozechner/pi-coding-agent).
 *
 * Key differences from the Claude adapter:
 * - Pi reads .claude/CLAUDE.md natively — overlay system works unchanged
 * - Guards are TypeScript extensions, not JSON hook configs
 * - RPC mode (--mode rpc) enables bidirectional control via stdin/stdout
 * - Model is passed as --model flag with provider-qualified names
 * - 324+ models across 20+ providers — no gateway workaround needed
 * - Pi's system prompt is ~200 tokens (vs Claude Code's ~10k)
 *
 * Phase 3: Pi adapter. Callers (sling.ts, coordinator.ts) use this via
 * `getRuntime("pi")` from the registry.
 */
export class PiRuntime implements AgentRuntime {
	/** Unique identifier for this runtime. */
	readonly id = "pi";

	/**
	 * Relative path to the instruction file within a worktree.
	 *
	 * Pi reads .claude/CLAUDE.md natively (traverses .claude/ directory at startup),
	 * so we reuse the same path as the Claude adapter. This means the existing
	 * overlay generator works without modification.
	 */
	readonly instructionPath = ".claude/CLAUDE.md";

	/**
	 * Build the shell command string to spawn an interactive Pi agent in a tmux pane.
	 *
	 * Maps SpawnOpts to the `pi` CLI flags:
	 * - `model` → `--model <model>`
	 * - `permissionMode` → ignored (Pi has no built-in permission gate; guards
	 *   are enforced by the deployed extension instead)
	 * - `appendSystemPrompt` → `--append-system-prompt '<escaped>'`
	 *
	 * Pi extensions are loaded via the `-e` flag. The guard extension is deployed
	 * to `.pi/extensions/overstory-guard.ts` by `deployConfig()`.
	 *
	 * The returned string is passed to tmux as the initial command.
	 *
	 * @param opts - Spawn options (model, appendSystemPrompt)
	 * @returns Shell command string suitable for tmux new-session
	 */
	buildSpawnCommand(opts: SpawnOpts): string {
		let cmd = `pi --model ${opts.model}`;

		// Load the guard extension we deployed to the worktree
		cmd += " -e .pi/extensions/overstory-guard.ts";

		if (opts.appendSystemPrompt) {
			const escaped = opts.appendSystemPrompt.replace(/'/g, "'\\''");
			cmd += ` --append-system-prompt '${escaped}'`;
		}

		return cmd;
	}

	/**
	 * Build the argv array for a headless one-shot Pi invocation.
	 *
	 * Pi's `--mode json` runs the prompt and exits, writing the response to
	 * stdout. This is used by merge/resolver.ts and watchdog/triage.ts for
	 * AI-assisted operations that don't need a full TUI session.
	 *
	 * @param prompt - The prompt to process
	 * @param model - Optional model override
	 * @returns Argv array for Bun.spawn
	 */
	buildPrintCommand(prompt: string, model?: string): string[] {
		const cmd = ["pi", "--mode", "json", "-p", prompt];
		if (model !== undefined) {
			cmd.push("--model", model);
		}
		return cmd;
	}

	/**
	 * Deploy per-agent instructions and guard extension to a worktree.
	 *
	 * For Pi this creates:
	 * 1. `.claude/CLAUDE.md` — task overlay (Pi reads this natively)
	 * 2. `.pi/extensions/overstory-guard.ts` — guard extension that enforces
	 *    path boundaries, capability restrictions, and dangerous command blocking
	 *
	 * The guard extension replaces Claude Code's settings.local.json hooks.
	 * Pi's extension system is more powerful: it can block, modify, or transform
	 * any tool call in-process rather than shelling out to external scripts.
	 *
	 * @param worktreePath - Absolute path to the agent's git worktree
	 * @param overlay - Overlay content for CLAUDE.md, or undefined for guard-only
	 * @param hooks - Guard configuration (agentName, capability, worktreePath)
	 */
	async deployConfig(
		worktreePath: string,
		overlay: OverlayContent | undefined,
		hooks: HooksDef,
	): Promise<void> {
		// Write overlay (Pi reads .claude/CLAUDE.md natively)
		if (overlay) {
			const claudeDir = join(worktreePath, ".claude");
			await mkdir(claudeDir, { recursive: true });
			await Bun.write(join(claudeDir, "CLAUDE.md"), overlay.content);
		}

		// Deploy guard extension
		const extDir = join(worktreePath, ".pi", "extensions");
		await mkdir(extDir, { recursive: true });

		const guardSource = generateGuardExtension(hooks);
		await writeFile(join(extDir, "overstory-guard.ts"), guardSource, "utf-8");
	}

	/**
	 * Detect Pi TUI readiness from a tmux pane content snapshot.
	 *
	 * Pi's TUI prompt indicator is ">" (the default input prompt character).
	 * Pi also shows model info in the footer when fully loaded. Unlike Claude
	 * Code, Pi has no trust dialog — it starts directly in ready state.
	 *
	 * Detection:
	 * - Footer with model name or context meter → `{ phase: "ready" }`
	 * - Otherwise → `{ phase: "loading" }`
	 *
	 * Note: For Pi in --mode rpc, readiness is detected via the RPC protocol
	 * (not tmux pane scraping). This method covers interactive TUI mode only.
	 *
	 * @param paneContent - Captured tmux pane content to analyze
	 * @returns Current readiness phase
	 */
	detectReady(paneContent: string): ReadyState {
		// Pi has no trust dialog — skip straight to readiness detection.

		// Pi's TUI shows the model name in the footer once fully loaded.
		// The input prompt shows ">" or a custom prompt character.
		const hasPrompt = paneContent.includes(">") || paneContent.includes("❯");

		// Pi's minimal extension shows a context meter like [###-------]
		// The footer also shows the model name (e.g., "claude-sonnet-4")
		const hasFooter =
			paneContent.includes("[#") || // context meter
			paneContent.includes("claude-") ||
			paneContent.includes("gpt-") ||
			paneContent.includes("gemini-") ||
			paneContent.includes("model:");

		if (hasPrompt && hasFooter) {
			return { phase: "ready" };
		}

		// Pi starts fast (~200 token system prompt). If we see a prompt
		// character but no footer, it may still be loading extensions.
		if (hasPrompt) {
			// Pi has no dialog phase. If there's a prompt, it's either
			// loading or ready. Give it the benefit of the doubt.
			return { phase: "ready" };
		}

		return { phase: "loading" };
	}

	/**
	 * Parse a Pi session transcript into normalized token usage.
	 *
	 * Pi sessions are stored as JSONL files with message entries that include
	 * usage data. The session file location depends on Pi's configuration
	 * but defaults to a temp directory.
	 *
	 * Pi's session format includes entries like:
	 * ```jsonl
	 * {"type":"message","role":"assistant","usage":{"inputTokens":1234,"outputTokens":567},"model":"claude-sonnet-4"}
	 * ```
	 *
	 * @param path - Absolute path to the Pi session JSONL file
	 * @returns Aggregated token usage, or null if unavailable
	 */
	async parseTranscript(path: string): Promise<TranscriptSummary | null> {
		const file = Bun.file(path);
		if (!(await file.exists())) {
			return null;
		}

		try {
			const content = await file.text();
			let inputTokens = 0;
			let outputTokens = 0;
			let model = "";

			for (const line of content.split("\n")) {
				if (!line.trim()) continue;
				try {
					const entry = JSON.parse(line) as {
						type?: string;
						role?: string;
						usage?: { inputTokens?: number; outputTokens?: number };
						model?: string;
					};

					if (entry.usage) {
						inputTokens += entry.usage.inputTokens ?? 0;
						outputTokens += entry.usage.outputTokens ?? 0;
					}
					if (entry.model) {
						model = entry.model;
					}
				} catch {
					// Skip unparseable lines
				}
			}

			if (inputTokens === 0 && outputTokens === 0) {
				return null;
			}

			return { inputTokens, outputTokens, model };
		} catch {
			return null;
		}
	}

	/**
	 * Build runtime-specific environment variables for model/provider routing.
	 *
	 * Pi supports 20+ providers natively. The resolved model's env vars are
	 * passed through directly — Pi handles provider routing internally based
	 * on the model name or --provider flag.
	 *
	 * For Anthropic: ANTHROPIC_API_KEY
	 * For OpenAI: OPENAI_API_KEY
	 * For Google: GEMINI_API_KEY
	 * For OpenRouter: OPENROUTER_API_KEY
	 * For gateways: the provider's authTokenEnv from config
	 *
	 * @param model - Resolved model with optional provider env vars
	 * @returns Environment variable map
	 */
	buildEnv(model: ResolvedModel): Record<string, string> {
		return model.env ?? {};
	}
}

/** Singleton instance for use in callers that do not need DI. */
export const piRuntime = new PiRuntime();
